### ISSUE TITLE
v4.3.2-1 segfaulting on Raspi Zero (armv6) on Raspibian 9.13 - Stretch

### ISSUE THREAD

**Issue by leoheck** [Motion-Project/motion#1309]
0. Reviewed guide and contributing documents? No
1. version [x.y.z, hash, other]: 4.3.2-1
2. installed as a package or compiled from sources [deb, rpm, git, other]: `stretch_motion_4.3.2-1_armhf.deb`
3. standalone or part of third party [motion, MotionEyeOS, other]: package
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: raspi webcam rev 1.3
5. hardware [x86, ARM, other]: armv6 
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Stetch

Tried to install the latest version on a Raspi Zero.
Installation went well but when running it I am seeing a segfault.
This is the end of commend when running with `strace`

```
protect(0xb296d000, 282624, PROT_READ) = 0
mprotect(0xb2db6000, 12288, PROT_READ)  = 0
mmap2(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xaed0c000
mprotect(0xb2b6b000, 12288, PROT_READ)  = 0
mprotect(0xb2dfa000, 4096, PROT_READ)   = 0
mprotect(0xb2e73000, 12288, PROT_READ)  = 0
mprotect(0xb4eb0000, 4096, PROT_READ)   = 0
mprotect(0xb4e9c000, 4096, PROT_READ)   = 0
mprotect(0xb33a9000, 4096, PROT_READ)   = 0
mprotect(0xb4e6d000, 4096, PROT_READ)   = 0
mprotect(0xb4e5a000, 4096, PROT_READ)   = 0
mprotect(0xb6eb9000, 61440, PROT_READ)  = 0
mprotect(0xb2e97000, 4096, PROT_READ)   = 0
mprotect(0xb2eb3000, 4096, PROT_READ)   = 0
mprotect(0xb3f8a000, 4096, PROT_READ)   = 0
mprotect(0xb2fa2000, 8192, PROT_READ)   = 0
mprotect(0xb301b000, 4096, PROT_READ)   = 0
mprotect(0xb32ba000, 16384, PROT_READ)  = 0
mprotect(0xb3303000, 4096, PROT_READ)   = 0
mprotect(0xb334e000, 4096, PROT_READ)   = 0
mprotect(0xb343c000, 4096, PROT_READ)   = 0
mprotect(0xb34c0000, 4096, PROT_READ)   = 0
mprotect(0xb3479000, 4096, PROT_READ)   = 0
mprotect(0xb34e0000, 4096, PROT_READ)   = 0
mprotect(0xb3521000, 4096, PROT_READ)   = 0
mprotect(0xb357b000, 20480, PROT_READ)  = 0
mprotect(0xb522a000, 32768, PROT_READ)  = 0
mprotect(0xb35d3000, 4096, PROT_READ)   = 0
mprotect(0xb361d000, 4096, PROT_READ)   = 0
mprotect(0xb37df000, 61440, PROT_READ)  = 0
mprotect(0xb3852000, 12288, PROT_READ)  = 0
mprotect(0xb39ff000, 4096, PROT_READ)   = 0
mprotect(0xb39bb000, 4096, PROT_READ)   = 0
mprotect(0xb39cf000, 4096, PROT_READ)   = 0
mprotect(0xb39e3000, 4096, PROT_READ)   = 0
mprotect(0xb3ad0000, 4096, PROT_READ)   = 0
mprotect(0xb3f1d000, 4096, PROT_READ)   = 0
mprotect(0xb3ba0000, 8192, PROT_READ)   = 0
mprotect(0xb3c34000, 8192, PROT_READ)   = 0
mprotect(0xb3c79000, 4096, PROT_READ)   = 0
mprotect(0xb3dc3000, 12288, PROT_READ)  = 0
mprotect(0xb4324000, 4096, PROT_READ)   = 0
mprotect(0xb3f00000, 4096, PROT_READ)   = 0
mprotect(0xb3f36000, 4096, PROT_READ)   = 0
mprotect(0xb3f4d000, 4096, PROT_READ)   = 0
mprotect(0xb3f60000, 4096, PROT_READ)   = 0
mprotect(0xb3f77000, 4096, PROT_READ)   = 0
mprotect(0xb3fee000, 4096, PROT_READ)   = 0
mprotect(0xb6f37000, 4096, PROT_READ)   = 0
mprotect(0xb6f50000, 4096, PROT_READ)   = 0
mprotect(0xb4b77000, 8192, PROT_READ)   = 0
mprotect(0xb4b43000, 24576, PROT_READ)  = 0
mprotect(0xb4a5a000, 4096, PROT_READ)   = 0
mprotect(0xb49cd000, 8192, PROT_READ)   = 0
mprotect(0xb4702000, 4096, PROT_READ)   = 0
mprotect(0xb4615000, 4096, PROT_READ)   = 0
mprotect(0xb45df000, 4096, PROT_READ)   = 0
mprotect(0xb4417000, 4096, PROT_READ)   = 0
mprotect(0xb43eb000, 4096, PROT_READ)   = 0
mprotect(0xb43a5000, 4096, PROT_READ)   = 0
mprotect(0xb437e000, 4096, PROT_READ)   = 0
mprotect(0xb4358000, 4096, PROT_READ)   = 0
mprotect(0xb433f000, 4096, PROT_READ)   = 0
mprotect(0xb42d1000, 4096, PROT_READ)   = 0
mprotect(0xb425e000, 4096, PROT_READ)   = 0
mprotect(0xb64bd000, 147456, PROT_READ) = 0
mprotect(0xb4e45000, 4096, PROT_READ)   = 0
mprotect(0xb4d84000, 8192, PROT_READ)   = 0
mprotect(0xb4c5a000, 8192, PROT_READ)   = 0
mprotect(0xb4c0c000, 4096, PROT_READ)   = 0
mprotect(0xb4bb8000, 4096, PROT_READ)   = 0
mprotect(0xb4b98000, 4096, PROT_READ)   = 0
mprotect(0xb6e28000, 69632, PROT_READ)  = 0
mprotect(0xb59e2000, 4096, PROT_READ)   = 0
mprotect(0xb4198000, 212992, PROT_READ) = 0
mprotect(0xb5462000, 8192, PROT_READ)   = 0
mprotect(0xb5499000, 8192, PROT_READ)   = 0
mprotect(0xb58cf000, 20480, PROT_READ)  = 0
mprotect(0xb596a000, 12288, PROT_READ)  = 0
mprotect(0xb6f76000, 4096, PROT_READ)   = 0
mprotect(0xb6fbc000, 4096, PROT_READ)   = 0
mprotect(0x4a0000, 4096, PROT_READ)     = 0
mprotect(0xb6fee000, 4096, PROT_READ)   = 0
munmap(0xb6fe3000, 44067)               = 0
set_tid_address(0xaed0e068)             = 4819
set_robust_list(0xaed0e070, 12)         = 0
rt_sigaction(SIGRTMIN, {sa_handler=0xb55592b0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0xb52606c0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0xb5559390, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0xb52606c0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
ugetrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
statfs("/sys/fs/selinux", 0xbe92753c)   = -1 ENOENT (No such file or directory)
statfs("/selinux", 0xbe92753c)          = -1 ENOENT (No such file or directory)
brk(NULL)                               = 0x860000
brk(0x881000)                           = 0x881000
open("/proc/filesystems", O_RDONLY)     = 3
fstat64(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "nodev\tsysfs\nnodev\ttmpfs\nnodev\tbd"..., 1024) = 310
read(3, "", 1024)                       = 0
close(3)                                = 0
access("/etc/selinux/config", F_OK)     = -1 ENOENT (No such file or directory)
gettimeofday({tv_sec=1612196544, tv_usec=682041}, NULL) = 0
open("/proc/self/auxv", O_RDONLY)       = 3
read(3, "\20\0\0\0\326\201\0\0", 8)     = 8
read(3, "\6\0\0\0\0\20\0\0", 8)         = 8
read(3, "\21\0\0\0d\0\0\0", 8)          = 8
read(3, "\3\0\0\0004\0E\0", 8)          = 8
read(3, "\4\0\0\0 \0\0\0", 8)           = 8
read(3, "\5\0\0\0\t\0\0\0", 8)          = 8
read(3, "\7\0\0\0\0\340\373\266", 8)    = 8
read(3, "\10\0\0\0\0\0\0\0", 8)         = 8
read(3, "\t\0\0\0!pE\0", 8)             = 8
read(3, "\v\0\0\0\350\3\0\0", 8)        = 8
read(3, "\f\0\0\0\350\3\0\0", 8)        = 8
read(3, "\r\0\0\0\350\3\0\0", 8)        = 8
read(3, "\16\0\0\0\350\3\0\0", 8)       = 8
read(3, "\27\0\0\0\0\0\0\0", 8)         = 8
read(3, "\31\0\0\0\211w\222\276", 8)    = 8
read(3, "\32\0\0\0\0\0\0\0", 8)         = 8
read(3, "\37\0\0\0\354\177\222\276", 8) = 8
read(3, "\17\0\0\0\231w\222\276", 8)    = 8
read(3, "\0\0\0\0\0\0\0\0", 8)          = 8
read(3, "", 8)                          = 0
close(3)                                = 0
open("/sys/devices/system/cpu", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents64(3, /* 13 entries */, 32768)  = 392
getdents64(3, /* 0 entries */, 32768)   = 0
close(3)                                = 0
sched_getaffinity(4819, 4, [0])         = 4
futex(0xb399f290, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0xb399f294, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0xb3580b68, FUTEX_WAKE_PRIVATE, 2147483647) = 0
getrandom("n", 1, GRND_NONBLOCK)        = 1
stat64("/etc/gnutls/default-priorities", 0xbe927560) = -1 ENOENT (No such file or directory)
brk(0x8a6000)                           = 0x8a6000
brk(0x8a0000)                           = 0x8a0000
access("/etc/gcrypt/fips_enabled", F_OK) = -1 ENOENT (No such file or directory)
open("/proc/sys/crypto/fips_enabled", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/etc/gcrypt/hwf.deny", O_RDONLY)  = -1 ENOENT (No such file or directory)
open("/proc/self/auxv", O_RDONLY)       = 3
fstat64(3, {st_mode=S_IFREG|0400, st_size=0, ...}) = 0
read(3, "\20\0\0\0\326\201\0\0\6\0\0\0\0\20\0\0\21\0\0\0d\0\0\0\3\0\0\0004\0E\0"..., 1024) = 152
read(3, "", 1024)                       = 0
close(3)                                = 0
open("/proc/cpuinfo", O_RDONLY)         = 3
fstat64(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "processor\t: 0\nmodel name\t: ARMv6"..., 1024) = 331
read(3, "", 1024)                       = 0
close(3)                                = 0
clock_gettime(CLOCK_MONOTONIC_COARSE, {tv_sec=59795, tv_nsec=48025718}) = 0
gettimeofday({tv_sec=1612196545, tv_usec=65601}, NULL) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x4a61e6} ---
+++ killed by SIGSEGV +++
[1]    4817 segmentation fault  strace motion
```

**Comment by leoheck** [comment]
Testing version 4.2.2, and it works.

**Comment by tosiara** [comment]
Can you run gdb and get backtrace of the crash?

**Comment by leoheck** [comment]
Yeap, I can do that. 
> Can you run gdb and get backtrace of the crash?
Do you have better instruction on what do you need to debug this or it is enough to run it with gdb until it fails?

I was using a config file for version `4.1.1` maybe this was the culprit.
I saw warnings about these new config items when executing version 4.2.2, then I updated them accordingly.
I have no more warnings running version `4.2.2`.

**Comment by leoheck** [comment]
Extra info about hardware, kernel, os

```
➜  ~ cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 9000c1
Serial		: 00000000859355d3
Model		: Raspberry Pi Zero W Rev 1.1

➜  ~ uname -a
Linux peephole 5.10.11+ #1399 Thu Jan 28 12:02:28 GMT 2021 armv6l GNU/Linux

➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch
```

I am installing this release: `stretch_motion_4.3.2-1_armhf.deb`

First try without any other info about how shoul I ran it... 

```
➜  ~ gdb $(which motion) | tee gdb_stretch_motion_4.3.2-1_armhf.log
GNU gdb (Raspbian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/motion...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/motion 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x004561e6 in ?? ()
(gdb) 
```

**Comment by tosiara** [comment]
When you see this output:
```
Program received signal SIGSEGV, Segmentation fault.
0x004561e6 in ?? ()
(gdb) 
```
type in `backtrace` and hit Enter

**Comment by leoheck** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x004561e6 in ?? ()
(gdb) backtrace
#0  0x004561e6 in ?? ()
#1  0x00407032 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by genius3000** [comment]
As it seems to pretty much not run at all, I'm inclined to say this is an architecture mismatch. A little Googling lead me to [this](https://raspberrypi.stackexchange.com/questions/87392/pi1-armv6-how-to-disable-armhf-packages).  
Basically, the `pi` (or Raspbian) packaging label of `armhf` will work with armv6, even claiming all RPis. The standard or Debian meaning of `armhf` is armv7 (and on?).

**Comment by leoheck** [comment]
Maybe you are right. 
I am using this `pi_stretch_motion_4.2.2-1_armhf.deb` and it works
However this one `stretch_motion_4.3.2-1_armhf.deb` is the one that is not working.
See the difference, the one that is working on has this `pi_` in front. Maybe this has something to do with what you are saying. 
Am I right?

**Comment by leoheck** [comment]
Cool I was able to compare binaries with this command

- Version 4.2.2 that works for me.
```
➜  ~ readelf -a -W $(which motion) | grep Tag
  Tag        Type                         Name/Value
  Tag_CPU_name: "ARM1176JZF-S"
  Tag_CPU_arch: v6KZ <=====================================
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_FP_arch: VFPv2
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_Virtualization_use: TrustZone
```

Version 4.3.2-1 that is not working
```
➜  ~ readelf -a -W lala/usr/bin/motion | grep Tag 
  Tag        Type                         Name/Value
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7 <===============================
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
➜  ~ 
```

Is it possible to have a realiease for Raspberry Zero (ARMv6 ?)

**Comment by leoheck** [comment]
@tosiara any chance to generate this different new release that is missing?

**Comment by tosiara** [comment]
I will look into this

**Comment by tosiara** [comment]
I don't have Raspberry Zero and Docker Hub has no Debian image for such architecture (arm32v6).
So I only could build for arm32v5 and arm32v7

**Comment by tosiara** [comment]
Just of out curiosity, can you try these builds?
[stretch_motion_4.3.2-1_armel.zip](https://github.com/Motion-Project/motion/files/5982330/stretch_motion_4.3.2-1_armel.zip)
[buster_motion_4.3.2-1_armel.zip](https://github.com/Motion-Project/motion/files/5982331/buster_motion_4.3.2-1_armel.zip)

**Comment by leoheck** [comment]
Testing this `stretch_motion_4.3.2-1_armel.zip`, unfortunately, it doesn't work.
![image](https://user-images.githubusercontent.com/1277920/108062503-a560dc00-7038-11eb-95ab-3fca8f19b09a.png)

> I don't have Raspberry Zero

How long it usually takes to build on the slowest board/system?
Maybe I can build it too. If I can, do you have instructions to make a deb file?

**Comment by leoheck** [comment]
I was able to build it easily. It took more or less 5 minutes. I was expecting hours.
> make  206.48s user 11.55s system 64% cpu 5:39.73 total

```
   **************************
      Configure status       
      motion 4.3.1+git20210125-34091a7
   **************************

CFLAGS: -D_THREAD_SAFE   -I/usr/include/p11-kit-1     -Irasppicam -I/opt/vc/include   -I/usr/include/arm-linux-gnueabihf   -g -O2

LIBS:  -pthread   -ljpeg   -lmicrohttpd   -lwebpmux -lwebp   -L/opt/vc/lib -lmmal -lmmal_core -lmmal_util -lmmal_vc_client -lbcm_host -lvcsm -lvcos   -lvchostif  -lavutil -lavformat -lavcodec -lswscale  -lavdevice  

LDFLAGS:  


OS                  : linux-gnueabihf
pthread_np          : no
pthread_setname_np  : yes
pthread_getname_np  : yes
XSI error           : no
webp support        : yes
V4L2 support        : yes
BKTR support        : no
MMAL support        : yes
FFmpeg support      : yes
libavformat version : 57.56.101
SQLite3 support     : no
MYSQL support       : no
PostgreSQL support  : no
MariaDB support     : no

Install prefix:       /usr/local
```

I could generate a deb file to release it here, what do you think? I just need some instructions to follow up

**Comment by tosiara** [comment]
Actually, we do have build for Pi and it seems to have v6, exactly what you were looking for
Have you tried it?
https://github.com/Motion-Project/motion/releases/tag/release-4.3.2
`pi_buster_motion_4.3.2-1_armhf.deb`

**Comment by leoheck** [comment]
I believe I tried that. I remember the issue was the OS version. Mine is
Strech, then the binary was complaining that something was missing.
I will test this again later when I get bet to home.
If that is the case, is it possible to generate a version for Strech?

--
Leandro Heck

**Comment by tosiara** [comment]
We use automated docker build script, that builds all available Debian and Ubuntu architectures: `amd64 i386 arm64v8 arm32v7`
To build Pi version I used an emulator which came with Buster as latest available.
You can always build your own deb by using simple script on the target device: https://github.com/Motion-Project/motion-packaging
