### ISSUE TITLE
Crash in netcam_rtsp_open_context

### ISSUE THREAD

**Issue by jogu** [Motion-Project/motion#224]
There's another crash I'm seeing relatively often (a few times a week); this is in a tree with the suggested fixes for #206 and #194 applied however I don't believe either of those is the root cause of this issue.

crash is here:

```
#0  0x00007f8e861db53c in ?? ()
   from /usr/lib/x86_64-linux-gnu/libavformat.so.56
#1  0x00007f8e861dbc1d in av_read_frame ()
   from /usr/lib/x86_64-linux-gnu/libavformat.so.56
#2  0x000000000042567c in netcam_read_rtsp_image (netcam=0x7f8e48000960)
    at netcam_rtsp.c:335
#3  0x0000000000425d89 in netcam_rtsp_open_context (netcam=0x7f8e48000960)
    at netcam_rtsp.c:559
#4  0x000000000042610e in netcam_connect_rtsp (
    netcam=netcam@entry=0x7f8e48000960) at netcam_rtsp.c:767
#5  0x000000000041351e in netcam_handler_loop (arg=0x7f8e48000960)
    at netcam.c:2015
#6  0x00007f8e873570a4 in start_thread (arg=0x7f8dfdffb700)
    at pthread_create.c:309
#7  0x00007f8e848ef87d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```
gdb in netcam_read_rtsp_image  claims:

```
(gdb) p netcam->rtsp->format_context
$8 = (AVFormatContext *) 0x0

```
A NULL format_context seems bad.

The logging for the problem camera is (NB: some of this logging is additional lines I've added):

```
[4:ml4:conservator] [NTC] [EVT] [Oct 05 07:12:39] event_newfile: File of type 1 saved to: /home/joseph/public_html/motion/snapshot/conservatory/20161005/071238-24-04.jpg
[4:ml4:conservator] [NTC] [EVT] [Oct 05 07:12:39] event_newfile: File of type 1 saved to: /home/joseph/public_html/motion/snapshot/conservatory/20161005/071239-24-00.jpg
[4:ml4:conservator] [NTC] [EVT] [Oct 05 07:12:39] event_newfile: File of type 1 saved to: /home/joseph/public_html/motion/snapshot/conservatory/20161005/071239-24-01.jpg
[4:ml4:conservator] [NTC] [EVT] [Oct 05 07:12:39] event_newfile: File of type 1 saved to: /home/joseph/public_html/motion/snapshot/conservatory/20161005/071239-24-02.jpg
[4:ml4:conservator] [NTC] [EVT] [Oct 05 07:12:40] event_newfile: File of type 1 saved to: /home/joseph/public_html/motion/snapshot/conservatory/20161005/071239-24-03.jpg
[4:ml4:conservator] [NTC] [EVT] [Oct 05 07:12:40] event_newfile: File of type 1 saved to: /home/joseph/public_html/motion/snapshot/conservatory/20161005/071239-24-04.jpg
[4:ml4:conservator] [NTC] [EVT] [Oct 05 07:12:40] event_newfile: File of type 1 saved to: /home/joseph/public_html/motion/snapshot/conservatory/20161005/071240-24-00.jpg
[4:nc4:conservator] [WRN] [NET] [Oct 05 07:13:15] netcam_interrupt_rtsp: Camera timed out for rtsp://XXXX@192.168.1.28:554/cam/realmonitor?channel=1&subtype=1
[4:nc4:conservator] [ERR] [ENC] [Oct 05 07:13:15] ffmpeg_avcodec_log: missing picture in access unit with size 24
[0:av4:conservator] [ERR] [ENC] [Oct 05 07:13:15] ffmpeg_avcodec_log: no frame!
[4:nc4:conservator] [WRN] [NET] [Oct 05 07:13:26] netcam_interrupt_rtsp: Camera timed out for rtsp://XXXX@192.168.1.28:554/cam/realmonitor?channel=1&subtype=1
[4:nc4:conservator] [ERR] [NET] [Oct 05 07:13:26] netcam_read_rtsp_image: line 358 calling netcam_rtsp_close_context
[4:nc4:conservator] [ERR] [NET] [Oct 05 07:13:26] netcam_rtsp_close_context: netcam_rtsp_close_context calling netcam_rtsp_null_context
[4:nc4:conservator] [ERR] [NET] [Oct 05 07:13:26] netcam_rtsp_null_context: netcam_rtsp_null_context NULLing codec_context
[4:nc4:conservator] [ERR] [NET] [Oct 05 07:13:26] netcam_handler_loop: Bad image.  Reconnecting with camera....
[4:ml4:conservator] [NTC] [ALL] [Oct 05 07:13:40] motion_loop: End of event 24
[4:ml4:conservator] [NTC] [ALL] [Oct 05 07:13:56] motion_loop: Video signal lost - Adding grey image
[4:nc4:conservator] [NTC] [ENC] [Oct 05 07:14:01] ffmpeg_avcodec_log: Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[4:nc4:conservator] [ERR] [NET] [Oct 05 07:14:01] netcam_rtsp_open_context: rtsp set codec_context to 0x135fc20
[4:ml4:conservator] [ERR] [ENC] [Oct 05 07:14:01] ffmpeg_avcodec_log: Picture size 0x0 is invalid
[4:ml4:conservator] [ERR] [NET] [Oct 05 07:14:01] netcam_rtsp_resize: line 681 calling netcam_rtsp_close_context
[4:ml4:conservator] [ERR] [NET] [Oct 05 07:14:01] netcam_rtsp_close_context: netcam_rtsp_close_context calling netcam_rtsp_null_context
[4:ml4:conservator] [ERR] [NET] [Oct 05 07:14:01] netcam_rtsp_null_context: netcam_rtsp_null_context NULLing codec_context
[4:ml4:conservator] [NTC] [ALL] [Oct 05 07:14:01] motion_loop: Video signal re-acquired
[4:ml4:conservator] [NTC] [EVT] [Oct 05 07:14:01] event_new_video Source FPS 5
[4:ml4:conservator] [NTC] [ENC] [Oct 05 07:14:01] ffmpeg_open Selected Output FPS 5
```

Note that there's two different threads here - "nc4" and "ml4" - respectively the netcam_handler_loop thread and the motion_loop thread for this camera.

It appears that the motion loop thread is disconnected the camera whilst the netcam thread is inside netcam_rtsp_open_context. It is not surprising that the netcam thread then crashes.

I think the root cause here could be the same as #207, namely this bit of code:

```
int netcam_next_rtsp(unsigned char *image , netcam_context_ptr netcam){

    if ((netcam->width  != (unsigned)netcam->rtsp->codec_context->width) ||
        (netcam->height != (unsigned)netcam->rtsp->codec_context->height) ||
        (netcam_check_pixfmt(netcam) != 0) ){
        netcam_rtsp_resize(image ,netcam);
    } else {
        memcpy(image, netcam->latest->ptr, netcam->latest->used);
    }
    if (netcam->cnt->rotate_data.degrees > 0)
        /* Rotate as specified */
        rotate_map(netcam->cnt, image);

    return 0;
}

```
[ifdefs removed for clarity]

I don't think it is safe to call netcam_rtsp_resize from this function which is called from the motion_loop thread (because it could result in the camera being disconnected whilst the netcam thread is trying to connect it, causing this bug), nor do I think it is safe for the motion_loop thread to access netcam->rtsp->codec_context here, as the netcam thread could NULL codec_context at any time (causing bug #207).

This code was introduced by:

> commit de77c45abc57d3f629ce13f966f937384967dcec
> Author: Mr Dave <dave@ubuntu.(none)>
> Date:   Sun Aug 10 20:47:11 2014 -0700
> 
>     RTSP rotate/resize/non YUV420/MJPEG. Now requires libswscale-dev
> 

I'm not sure what the fix is. I think I may need some help from @Mr-Dave . I wonder if all rotation & resizing should be moved to the netcam thread, simplifying the code running on the motion_loop thread back to a simple memcpy of the image.

**Comment by Mr-Dave** [comment]
I agree with your assessment that it needs to move and be inside the netcam thread.  Seeing the trace makes all the difference......
