### ISSUE TITLE
Can't connect to rtsp feed

### ISSUE THREAD

**Issue by chumy76** [Motion-Project/motion#353]
I have installed motioeyeos on a rpi3, this works fine. I have done a manual install following instructions on a rpi3, this also worked fine.

I have followed instructions to install on debian and ubuntu (both latest distro) and cannot get the video feed to work on any of them. I know the connection info is correct as still running on the rpi3.

Logs show:

code/ [2:ml2] [DBG] [ALL] motion_loop: vid_return_code 1
[1:ml1] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[1:ml1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.1.2:554/VideoMain)
[1:ml1] [DBG] [NET] netcam_url_parse: Entry netcam_url_parse data rtsp://192.168.1.2:554/VideoMain
[1:ml1] [DBG] [NET] netcam_url_parse: Parse case 0 data rtsp://192.168.1.2:554/VideoMain
[1:ml1] [DBG] [NET] netcam_url_parse: Parse case 1 data rtsp
[1:ml1] [DBG] [NET] netcam_url_parse: Parse case 6 data 192.168.1.2
[1:ml1] [DBG] [NET] netcam_url_parse: Parse case 7 data :554
[1:ml1] [DBG] [NET] netcam_url_parse: Parse case 8 data 554
[1:ml1] [DBG] [NET] netcam_url_parse: Parse case 9 data /VideoMain
[1:ml1] [INF] [NET] netcam_start: Netcam_http parameter 'off' converts to flags: HTTP/1.0: 1 HTTP/1.1: 0 Keep-Alive O
[1:ml1] [INF] [NET] netcam_start: now calling netcam_setup_rtsp()
[1:ml1] [NTC] [NET] netcam_rtsp_open_context: Using tcp transport
[2:ml2] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[2:ml2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.1.2:554/VideoMain)
[2:ml2] [DBG] [NET] netcam_url_parse: Entry netcam_url_parse data rtsp://192.168.1.2:554/VideoMain
[2:ml2] [DBG] [NET] netcam_url_parse: Parse case 0 data rtsp://192.168.1.2:554/VideoMain
[2:ml2] [DBG] [NET] netcam_url_parse: Parse case 1 data rtsp
[2:ml2] [DBG] [NET] netcam_url_parse: Parse case 6 data 192.168.1.2
[2:ml2] [DBG] [NET] netcam_url_parse: Parse case 7 data :554
[2:ml2] [DBG] [NET] netcam_url_parse: Parse case 8 data 554
[2:ml2] [DBG] [NET] netcam_url_parse: Parse case 9 data /VideoMain
[2:ml2] [INF] [NET] netcam_start: Netcam_http parameter 'off' converts to flags: HTTP/1.0: 1 HTTP/1.1: 0 Keep-Alive O
[2:ml2] [INF] [NET] netcam_start: now calling netcam_setup_rtsp()
[2:ml2] [NTC] [NET] netcam_rtsp_open_context: Using tcp transport
[1:ml1] [ERR] [ENC] ffmpeg_avcodec_log: method DESCRIBE failed: 500 Internal Server Error
[1:ml1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://usr:pwd@192.168.1.2:554/VideoMainver returned 5XX Server Error reply

I've removed user a pwd from log above.

As I said I've tried on debian and ubuntu on xenserver. I get the UI ok but cannot get a stream to work.

I reported on motioneye but they seem to think that the issue is with motion - in particular:

[1:ml1] [ERR] [ENC] ffmpeg_avcodec_log: method DESCRIBE failed: 500 Internal Server Error

When I enter cam url it detects it as a valid cam.

I have also tried to update motion to the latest but still no joy.
Cheers for any advice :-)

**Comment by tosiara** [comment]
Please follow instruction how to run motion standalone here: https://github.com/Motion-Project/motion/wiki/Related-Projects
When you reproduce the issue standalone, please post full log here

**Comment by ccrisan** [comment]
@tosiara thanks for providing additional instructions for running motion standalone on motionEye(OS).

I have just one small remark: when running motionEye (not the OS) on a regular Linux distro, things are a bit different:

    systemctl stop motioneye  # for systemd
    /etc/init.d/motioneye stop  # for sysvinit
    cd /etc
    motion -c motion.conf -d 6 -n

**Comment by tosiara** [comment]
Ok, updated the wiki: https://github.com/Motion-Project/motion/wiki/motioneye

**Comment by Mr-Dave** [comment]
@ccrisan: I do not believe that instruction for running is correct and is what is caused a incorrect issue to be reported here in #349.  @chumy76 You need to find the motion.conf file that corresponds to the Motioneye and specify the the full path and file name within the command line.  You will also probably need to use the [command line switches](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Command_Line_Options) to specify the full log file that we will need to be posted to determine the cause.

**Comment by chumy76** [comment]
Ok, need to try and understand that :-/  In the meantime I did run the stuff from the wiki page and got the following out of /var/log/user.log

Mar 12 17:31:20 debian motion: [1:ml1] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
Mar 12 17:31:20 debian motion: [1:ml1] [NTC] [VID] vid_v4lx_start: Using videodevice /dev/video0 and input -1
Mar 12 17:31:20 debian motion: [1:ml1] [ALR] [VID] vid_v4lx_start: Failed to open video device /dev/video0: No such file or directory

**Comment by ccrisan** [comment]
@Mr-Dave you're right: motionEye uses `/etc/motioneye/*.conf` for all configuration purposes, including `motion.conf` and `thread-*.conf`. I'll make sure to provide a wiki article or page or something to help users run motion standalone when motionEye complains.

**Comment by ccrisan** [comment]
@chumy76, in your case, just `cd /etc/motioneye` instead of `cd /etc` and then run the motion command.

**Comment by chumy76** [comment]
got it, might be me but don't see anything in the logs that is different: (this is outputted to the screen when I run the motion command)

[1:ml1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.1.2:554/VideoMain)
[1:ml1] [NTC] [NET] netcam_rtsp_open_context: Using tcp transport
[1:ml1] [ERR] [ENC] ffmpeg_avcodec_log: method DESCRIBE failed: 500 Internal Server Error
[1:ml1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://user:pwd@192.168.1.2:554/VideoMain): Server returned 5XX Server Error reply
[1:ml1] [NTC] [ALL] motion_loop: Video signal lost - Adding grey image
^C[1:ml1] [NTC] [ALL] motion_loop: End of event 1
curl: (7) Failed to connect to 127.0.0.1 port 8765: Connection refused
[0:web_control] [NTC] [STR] httpd_run: motion-httpd - Finishing
[0:web_control] [NTC] [STR] httpd_run: motion-httpd Closing
[0:web_control] [NTC] [STR] motion_web_control: motion-httpd thread exit
[1:ml1] [NTC] [ALL] motion_loop: Thread exiting
[1:ml1] [NTC] [STR] stream_stop: Closing motion-stream listen socket & active motion-stream sockets
[1:ml1] [NTC] [STR] stream_stop: Closed motion-stream listen socket & active motion-stream sockets
curl: (7) Failed to connect to 127.0.0.1 port 8765: Connection refused


Should I mention that I'm on a gen8 microserver running xenserver so debian is running as a VM?

**Comment by Mr-Dave** [comment]
Has the url been validated to be functional using vlc, ffplay etc on that computer?  Looks like a url, authentication issue.

**Comment by chumy76** [comment]
Not on that computer - no UI.  I have validated it on VLC on my windows machine and also on raspberry pi  using motioneyeos, let me look into ffplay

**Comment by chumy76** [comment]
vlc on gnome can't open stream either :-)  No idea what to do!

**Comment by carryonrewardless** [comment]
I have the same issue. Running 3.4.1 on Ubuntu 16.04 after trying the 3.2.12 default version. 
VLC command works:
rtsp://user:pwd@192.168.1.111/onvif2
Log looks like:
[0] [NTC] [ENC] [Mar 13 07:39:53] ffmpeg_init: ffmpeg LIBAVCODEC_BUILD 3685476 LIBAVFORMAT_BUILD 3680357
[0] [NTC] [ALL] [Mar 13 07:39:53] main: Thread 1 is from /etc/motion/motion.conf
[0] [NTC] [ALL] [Mar 13 07:39:53] main: Thread 1 is device: rtsp://admin:20160404@192.168.1.111:554/onvif2 input -1
[0] [NTC] [ALL] [Mar 13 07:39:53] main: Stream port 5000
[0] [NTC] [ALL] [Mar 13 07:39:53] main: Waiting for threads to finish, pid: 9833
[1] [NTC] [ALL] [Mar 13 07:39:53] motion_init: Thread 1 started , motion detection Enabled
[1] [ALR] [NET] [Mar 13 07:39:53] netcam_start: Network Camera thread starting... for url (rtsp://user:pwd@192.168.1.111:554/onvif2)
[0] [NTC] [STR] [Mar 13 07:39:53] httpd_run: motion-httpd testing : IPV4 addr: 0.0.0.0 port: 554
[0] [NTC] [STR] [Mar 13 07:39:53] httpd_run: motion-httpd Bound : IPV4 addr: 0.0.0.0 port: 554
[0] [NTC] [STR] [Mar 13 07:39:53] httpd_run: motion-httpd/3.4.1~rc01 running, accepting connections
[0] [NTC] [STR] [Mar 13 07:39:53] httpd_run: motion-httpd: waiting for data on 0.0.0.0 port TCP 554
[1] [NTC] [NET] [Mar 13 07:39:53] netcam_rtsp_open_context: Using tcp transport
[1] [ERR] [NET] [Mar 13 07:39:53] netcam_rtsp_open_context: unable to open input(rtsp://user:pwd@192.168.1.111:554/onvif2): Invalid data found when processing input
[1] [WRN] [ALL] [Mar 13 07:39:53] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
[1] [NTC] [ALL] [Mar 13 07:39:53] image_ring_resize: Resizing pre_capture buffer to 1 items
[1] [NTC] [STR] [Mar 13 07:39:53] http_bindsock: motion-stream testing : IPV4 addr: 0.0.0.0 port: 5000
[1] [NTC] [STR] [Mar 13 07:39:53] http_bindsock: motion-stream Bound : IPV4 addr: 0.0.0.0 port: 5000
[1] [NTC] [ALL] [Mar 13 07:39:53] motion_init: Started motion-stream server in port 5000 auth Disabled
[1] [WRN] [ALL] [Mar 13 07:40:00] motion_loop: Retrying until successful connection with camera

I notice it reports input -1 even though conf file says input 1.
Also tried on raspbian Jessie with same result.

**Comment by Mr-Dave** [comment]
This is not a problem with Motion code and is instead a problem with the parameter being specified.  I believe the best course of action is to ask the motion-user [mailing list](https://lists.sourceforge.net/lists/listinfo/motion-user).  You can also consult the [User guide](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#netcam_url) and [Contributing guide](https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md)

**Comment by chumy76** [comment]
@mr-dave was that in reply to whole thread or just last comment?  If its of any interest i did have rtsp working fine on vm with zoneminder installed. Didn't like it much.

**Comment by Mr-Dave** [comment]
It appears that each of the issues is a something related to the parameter, camera or network.  If VLC or ffplay can not open the camera, then it is highly likely it is a problem outside of Motion.  I would guess this is a network issue but I'm not a network expert and it would be better to ask this to a wider audience of the user list.

**Comment by carryonrewardless** [comment]
On 14/03/17 14:38, Mr-Dave wrote:
>
> It appears that each of the issues is a something related to the 
> parameter, camera or network. If VLC or ffplay can not open the camera
>

No No. Both ffplay and VLC _can_ open the camera and play and record.
>
> , then it is highly likely it is a problem outside of Motion. I would 
> guess this is a network issue
>
There is no camera problem and no network problem.

I will try turning of the rtsp_uses_tcp parameter as you suggested 
earlier and see how that goes.

**Comment by chumy76** [comment]
I trashed my VM and started again, new stuff in log:
 I can assure you that my credentials are fine: 

Mar 14 18:21:06 ubuntu motion: [2] [ALR] [NET] rtsp_connect: unable to open input(rtsp://192.168.1.3:554/VideoMain): -825242872 - Server returned 401 Unauthorized (authorization failed)
Mar 14 18:21:06 ubuntu kernel: [ 1859.858559] motion[21787]: segfault at 0 ip 00007f4c98a8d84f sp 00007f4c7fb58670 error 4 in libavutil-ffmpeg.so.54.31.100[7f4c98a7e000+56000]
Mar 14 18:21:06 ubuntu meyectl[21662]:    ERROR: failed to start motion: motion failed to start
Mar 14 18:21:06 ubuntu meyectl[21662]: Traceback (most recent call last):
Mar 14 18:21:06 ubuntu meyectl[21662]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/server.py", line 323, in checker
Mar 14 18:21:06 ubuntu meyectl[21662]:     motionctl.start()
Mar 14 18:21:06 ubuntu meyectl[21662]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/motionctl.py", line 134, in start
Mar 14 18:21:06 ubuntu meyectl[21662]:     raise Exception('motion failed to start')
Mar 14 18:21:06 ubuntu meyectl[21662]: Exception: motion failed to start
Mar 14 18:21:06 ubuntu meyectl[21662]:  WARNING: Connect error on fd 20: ECONNREFUSED
Mar 14 18:21:06 ubuntu meyectl[21662]:  WARNING: Connect error on fd 21: ECONNREFUSED
Mar 14 18:21:07 ubuntu meyectl[21662]:  WARNING: Connect error on fd 20: ECONNREFUSED
Mar 14 18:21:16 ubuntu meyectl[21662]: message repeated 17 times: [  WARNING: Connect error on fd 20: ECONNREFUSED]
Mar 14 18:21:16 ubuntu meyectl[21662]:    ERROR: motion not running, starting it
Mar 14 18:21:16 ubuntu motion: [14774656] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motioneye/motion.conf
Mar 14 18:21:16 ubuntu motion: [14774656] [NTC] [ALL] config_thread: Processing config file thread-1.conf
Mar 14 18:21:16 ubuntu motion: [14774656] [NTC] [ALL] config_thread: Processing config file thread-2.conf
Mar 14 18:21:16 ubuntu motion: [14774656] [NTC] [ALL] motion_startup: Motion 3.2.12+git20140228 Started with SDL support
Mar 14 18:21:16 ubuntu motion: [14774656] [NTC] [ALL] motion_startup: Logging to syslog
Mar 14 18:21:16 ubuntu motion: [14774656] [NTC] [ALL] motion_startup: Using default log type (ALL)
Mar 14 18:21:16 ubuntu motion: [14774656] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)

**Comment by chumy76** [comment]
I was using motioneye. Not quite figured out how to run motion standalone  as linux newbie. I did enter rtsp as mentioned. I think i might have thrown the towel  in now. All works fine when i install on rpi3 on rasbian or motioneyeos just don't know how many cameras rpi3 can handle. Did a fresh install of debian on xenserver  but still no joy. Grey feed. Maybe just doesn't work on xenserver!

**Comment by ccrisan** [comment]
@chumy76 we now have this [Report Motion Issue](https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue) wiki page to help you run motion outside of motionEye, so that you can collect the logs and files specific to motion.

**Comment by chumy76** [comment]
I tried the above but nothing gets created, no log file generated.  This was however after I upgraded motion to 4.0.1(how come this doesn't get pulled down with motioneye?).  Anyway could really do with some steps to properly upgrade to 4.0.1 so guess I'll have to start again from scratch!

**Comment by chumy76** [comment]
Files attached, managed to get some time to look at this today.  FYI I installed another program xeoma to test camera connectivity from server and all OK.

[motion-conf.txt](https://github.com/Motion-Project/motion/files/852382/motion-conf.txt)
[thread-1-conf.txt](https://github.com/Motion-Project/motion/files/852385/thread-1-conf.txt)
[motion-log.txt](https://github.com/Motion-Project/motion/files/852386/motion-log.txt)

**Comment by tosiara** [comment]
Your camera gives `Internal Server Error` response:
```
[1:ml1] [ERR] [ENC] ffmpeg_avcodec_log: method DESCRIBE failed: 500 Internal Server Error
[1:ml1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://user:pass@192.168.1.2:554/VideoMain): Server returned 5XX Server Error reply
```
That means that camera is not able to provide video stream for motion.
It could be some incompatibility between ffmpeg used by motion and your camera software. Maybe user/password passing?

Can you please try to run ffprobe of the same version (ffmpeg libavcodec version 56.60.100 libavformat version 56.40.101) with the same rstp url and post the results?

**Comment by jogu** [comment]
Closing as no response to tosiara's questions; reopen if there's more info.

**Comment by jandebleser** [comment]
In my case it helped to add `rtsp_uses_tcp off` to motion.conf
