### ISSUE TITLE
net cam rtsp passthrouigh SIGSEGV

### ISSUE THREAD

**Issue by PeterHolik** [Motion-Project/motion#843]
0. Reviewed guide and contributing documents? (Yes/No): no
1. version [x.y.z, hash, other]: 4.2+git
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cam rtsp
5. hardware [x86, ARM, other]:  x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: ubuntu

My Netcam disconnects every hour and sometimes i got a segmentation fault:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xac5d5b40 (LWP 15036)]
0x08077ec8 in netcam_rtsp_pktarray_add (rtsp_data=0xae3004c8) at netcam_rtsp.c:182
182<--->        rtsp_data->pktarray[indx_next].idnbr = rtsp_data->idnbr;
(gdb) bt
#0  0x08077ec8 in netcam_rtsp_pktarray_add (rtsp_data=0xae3004c8) at netcam_rtsp.c:182
#1  netcam_rtsp_read_image (rtsp_data=rtsp_data@entry=0xae3004c8) at netcam_rtsp.c:654
#2  0x08078e95 in netcam_rtsp_open_context (rtsp_data=0xae3004c8) at netcam_rtsp.c:1247
#3  netcam_rtsp_connect (rtsp_data=rtsp_data@entry=0xae3004c8) at netcam_rtsp.c:1263
#4  0x08079ec3 in netcam_rtsp_handler_reconnect (rtsp_data=rtsp_data@entry=0xae3004c8) at netcam_rtsp.c:1380
#5  0x0807a1b5 in netcam_rtsp_handler (arg=0xae3004c8) at netcam_rtsp.c:1411
#6  0xb5e2cf72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#7  0xb5d6343e in clone () from /lib/i386-linux-gnu/libc.so.6

(gdb) print rtsp_data->idnbr
$1 = 95
(gdb) print indx_next
$2 = 0
(gdb) print rtsp_data->pktarray[0]
Cannot access memory at address 0x0
(gdb) print rtsp_data->pktarray
$3 = (struct packet_item *) 0x0
(gdb) print rtsp_data->pktarray_index
$4 = -1

To see where and why this happens i added some logging:

motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_copy_stream: Stream copied for pass-through
motion: [2:ml2:hof] [INF] [NET] netcam_rtsp_pktarray_resize: Normal resolution: Resized packet (nil) to 0xae300668 size 0 to 30
motion: [3:nc3:hof] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera (hof) connected
motion: [2:ml2:hof] [INF] [NET] netcam_rtsp_pktarray_resize: Normal resolution: Resized packet 0xae300668 to 0xae301690 size 30 to 32
motion: [2:ml2:hof] [INF] [NET] netcam_rtsp_pktarray_resize: Normal resolution: Resized packet 0xae301690 to 0xae300668 size 32 to 38
motion: [2:ml2:hof] [INF] [NET] netcam_rtsp_pktarray_resize: Normal resolution: Resized packet 0xae300668 to 0xae302e78 size 38 to 50
motion: [2:ml2:hof] [INF] [NET] netcam_rtsp_pktarray_resize: Normal resolution: Resized packet 0xae302e78 to 0xae3caee8 size 50 to 60

motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_interrupt: Normal resolution: Camera reading (hof) timed out
motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_read_image: Normal resolution: av_read_frame: Success ,Interrupt: True
motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_interrupt: Normal resolution: Camera reading (hof) timed out
motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_close_context: Normal resolution: rtsp_close_context packet 0xae3caee8 array size 60
motion: [2:ml2:hof] [INF] [NET] netcam_rtsp_pktarray_resize: Normal resolution: Resized packet (nil) to 0xae300668 size 0 to 30
motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_null_context: Normal resolution: rtsp_null_context packet 0xae300668 array size 30
motion: [3:nc3:hof] [ERR] [NET] netcam_rtsp_handler_reconnect: Normal resolution: Reconnecting with camera....

motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_interrupt: Normal resolution: Camera (hof) timed out
motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_null_context: Normal resolution: rtsp_null_context packet (nil) array size 30

motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_open_context: Normal resolution: Opened camera(hof)

motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_copy_stream: Stream copied for pass-through
motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_pktarray_add: Normal resolution: add packet (nil) array size 30

The relevant lines are:

motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_close_context: Normal resolution: rtsp_close_context packet 0xae3caee8 array size 60
motion: [2:ml2:hof] [INF] [NET] netcam_rtsp_pktarray_resize: Normal resolution: Resized packet (nil) to 0xae300668 size 0 to 30
motion: [3:nc3:hof] [INF] [NET] netcam_rtsp_null_context: Normal resolution: rtsp_null_context packet 0xae300668 array size 30

rtsp_null_context only sets rtsp_data->pktarray  to NULL but not pktarray_size

A quick fix is

--- netcam_rtsp.c.orig	2018-11-16 09:32:07.128958031 +0100
+++ netcam_rtsp.c.fix	2018-11-16 09:32:17.299696109 +0100
@@ -72,7 +72,7 @@
     rtsp_data->frame           = NULL;
     rtsp_data->codec_context   = NULL;
     rtsp_data->format_context  = NULL;
-    rtsp_data->pktarray        = NULL;
+    if (rtsp_data->pktarray != NULL) netcam_rtsp_pktarray_free(rtsp_data);
     rtsp_data->transfer_format = NULL;
 
 }

But maybe there are other solutions also.

cu Peter

**Comment by Mr-Dave** [comment]
Do you have a full log that you can post at the inf level?  I think that there may be more to revise than just the line indicated and I'd also like to see if there is something going on with the disconnects.
